# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master", "*"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: 
        fetch-depth: 0
        
    - name: Get Latest Tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1
      
    - name: Print latest tag
      run: echo  ${{ steps.previoustag.outputs.tag }}

    - name: 'Get next versions formats'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
        
#    - name: Print next versions formats, all of them (major, minor, patch) and with v in the beginning
#      run: echo '${{ toJSON(steps.semvers.outputs) }}'

    - name: Set next patch version
      run: echo "next_patch_version=${{ steps.semvers.outputs.patch }}" >> "$GITHUB_ENV"
      
    - name: Print next patch version
      run: echo "$next_patch_version"

    - name: Replace the version in pom.xml
      run: |
        sed -i "0,/<version>.*<\/version>/s/<version>.*<\/version>/<version>${next_patch_version}<\/version>/" pom.xml
      working-directory: myapp
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn package
      working-directory: myapp
